package ru.meditron.routing.route.domain;

/** См. ROUTES-REQUIREMENTS v1.1. */
public enum CloseReason {
    SURGERY_NOT_INDICATED, PATIENT_REFUSED, OTHER_ORGANIZATION, TRANSFERRED, PROTOCOL_ANNULLED, FINDING_NOT_CONFIRMED, FINDING_REJECTED, PROTOCOL_CORRECTED
}
