package ru.meditron.routing.route.domain;

/** См. ROUTES-REQUIREMENTS v1.1. */
public enum RouteStage {
    CREATED, NOTIFIED, BOOKED, REBOOKING_REQUIRED, NO_SHOW, AWAITING_TACTIC, ADDITIONAL_EXAM, PROCEDURE_REFERRED, PROCEDURE_DONE, HOSPITALIZATION_REFERRED, HOSPITALIZATION_SCHEDULED, HOSPITALIZED, SURGERY_DONE, DISCHARGED, CONTROL_PENDING, OBSERVATION_WAITING_US, OBSERVATION_WAITING_VISIT, COMPLETED, CLOSED, NOT_ENGAGED
}
